---

# Possible upgrade is to slim this down to one task that accepts a variable
# from the include statement, so that the include statement says what variable
# it wants, and this processes the request and spits it back.

- name: register INSTALL_ROOT from /etc/courtlistener
  shell: ansible/get_vars.sh INSTALL_ROOT
  register: INSTALL_ROOT
  tags: setup, testing

- name: register CL_SOLR_XMX from /etc/courtlistener
  shell: ansible/get_vars.sh CL_SOLR_XMX
  register: CL_SOLR_XMX
  tags: setup, testing

- name: register VIRTUALENV_ROOT from /etc/courtlistener
  shell: ansible/get_vars.sh VIRTUALENV_ROOT
  register: VIRTUALENV_ROOT
  tags: setup, testing

- name: check if celery exists (or this is a dev machine)
  stat: path=/etc/init.d/celeryd
  register: celeryd_status
